### ISSUE TITLE
Let's handle passwords better

### ISSUE THREAD

**Issue by mattl** [cc-archive/techstuff#11]

**Comment by mattl** [comment]
@robmyers as an update to this, when we get our Yubikeys, I'd like to see how well they work. If they're good, let's get one for Sarah who's already using LastPass too. And then... roll them out.

**Comment by rheaplex** [comment]
I use my nano for personal accounts and it's great, although I'm always worried about losing it... Yes let's evaluate.

**Comment by mattl** [comment]
I genuinely thought you were using 'nano' to keep track of them. Emacs plz.

**Comment by mattl** [comment]
Let's discuss this next week.
