### ISSUE TITLE
Give Jess CiviCRM access

### ISSUE THREAD

**Issue by jessicacoates** [cc-archive/techstuff#2]
Not sure this is the right place - sorry if it's not! And sorry - can't seem to assign it for some reason?

**Comment by rheaplex** [comment]
You should now have access.

**Comment by jessicacoates** [comment]
I logged in, but it doesn't seem to give me access. Or I have the wrong link. See my email.

**Comment by rheaplex** [comment]
I've made you an administrator. That should giove you access to everything.

**Comment by mattl** [comment]
Jess, you should be able to login at https://donate.creativecommons.org/user and then access CiviCRM at https://donate.creativecommons.org/civicrm/ once logged in.

I'd like Rob and I to set up the registration stuff for the event if possible.

**Comment by jessicacoates** [comment]
Excellent! That worked. Thanks.

Very happy for you guys to do the form. Mari has agreed to lead on registration, so I'll start a thread for you all. There's already a form we've used for the past 2 Summits that you can use as the base: https://donate.creativecommons.org/civicrm/event/manage/registration?reset=1&action=update&id=9. 

I don't think we'd need to change much, unless you want to change something in the back end.
