### ISSUE TITLE
Respond to question re updating CC's RDF data in tech white paper

### ISSUE THREAD

**Issue by peterspdx** [cc-archive/techstuff#22]
Also opened in licenses/rdf project, for @mattl to respond:

dcterms:version
we are using dcterms:hasVersion, incorrectly, in the existing turtle.
Reply•Resolve

Antoine IsaacThat's right, and I can trace this back to CC's own license data: https://github.com/creativecommons/license.rdf/blob/master/cc/licenserdf/rdf/index.rdf 
+diane@creativecommons.org, matt@creativecommons.org, if we do use the DC properties in the right way, could it be possible to update CC's RDF data?

**Comment by mattl** [comment]
@robmyers let's discuss later.
