### ISSUE TITLE
Pre-4.0 jurisdiction ports and chooser linking to English deeds when offline work selected

### ISSUE THREAD

**Issue by peterspdx** [cc-archive/techstuff#23]
Cable, you identified this issue awhile back. We're cleaning up these issues with Mattl and robmeyers. We tested for this, and the problem seems fixed. Can you please let us know if you still experience a problem? Thanks!

License Mark: Offline: removing extraneous URL text
Go to the license chooser (current or Looking for ports of earlier versions?)
Select "Offline" in the "License Mark" filed (lower left quadrant)
Look at the text in the lower right quadrant.
This work is licensed under the Creative Commons Attribution 4.0 International License. To view a copy of this license, visit http://creativecommons.org/licenses/by/4.0/deed.en_US.
This URL text "/deed.en_US"
is unnecessary - this shorter, cleaner link takes one to the same license: http://creativecommons.org/licenses/by/4.0
looks US centric (bad optics for CC)
Recommend this extra text be removed for the English default license
Dan and I both discovered this extra text disappears if you click on "English" on the footer of the CC Chooser page.

**Comment by peterspdx** [comment]
cable_green: can you take a look and let Matt and me know if this is still problem?

**Comment by cablegreen** [comment]
Looks great! Thank you.
