### ISSUE TITLE
Thomas Margoni on CC-Commits email list 

### ISSUE THREAD

**Issue by jessicacoates** [cc-archive/techstuff#24]
Hi - Thomas Margoni would like us to change his address on the cc-commits mailing list to thomas.margoni@stir.ac.uk

**Comment by rheaplex** [comment]
They can update details here - http://lists.ibiblio.org/mailman/listinfo/cc-commits

If they don't have their password let me know and I'll see about doing this manually.

**Comment by jessicacoates** [comment]
What password can they use? The ibiblio accounts have always been done internally, as far as I'm aware - we've never asked people to add their own name, so I doubt he has an account. Matt just set up the list and added the names I gave him.

**Comment by mattl** [comment]
They can enter their current email address, it'll email them a password (we don't know it) and then they can change their email address.

**Comment by jessicacoates** [comment]
THanks guys - sending this to Thomas. I'll let you know if it doesn't work.
