### ISSUE TITLE
fix broken link on /policies page 

### ISSUE THREAD

**Issue by peterspdx** [cc-archive/techstuff#25]
this link: https://creativecommons.org/Affiliates, on our /policies page is leading to a random page. Should go to: https://wiki.creativecommons.org/wiki/Affiliates

**Comment by peterspdx** [comment]
Unsure why I can't assign this to someone, but @mattl  and @robmyers , this is for you :-)

**Comment by rheaplex** [comment]
I assigned myself. :-)

This has been updated.
