### ISSUE TITLE
CC gMail - CC logo

### ISSUE THREAD

**Issue by cablegreen** [cc-archive/techstuff#26]
In CC gMail - the CC logo in the upper right has been replaced with "Google."  

Is it possible to put the CC logo back in the upper left corner of CC mail?

**Comment by mattl** [comment]
![screenshot from 2015-10-22 15-22-41](https://cloud.githubusercontent.com/assets/33296/10677319/3d712c6c-78d1-11e5-937a-d0ba7a2a3493.png)

This was what I saw went I went to check. I guess our logo got corrupted or lost somehow.

Anyway, it's back.

**Comment by cablegreen** [comment]
Thanks!
