### ISSUE TITLE
CC Wiki: Cable can't delete CC Wiki pages

### ISSUE THREAD

**Issue by cablegreen** [cc-archive/techstuff#28]
Once logged in with my CC ID ... I can create and edit new CC Wiki pages ... but I cannot delete pages.

It would be helpful if CC staff could delete CC Wiki pages when needed (e.g., when I make a mistake and need to delete a page)

Thanks - Cable

**Comment by mattl** [comment]
Is this resolved?

**Comment by cablegreen** [comment]
Not resolved.

I re-created this page: https://wiki.creativecommons.org/wiki/Cable-green-test

I'm logged in

Click on "Page" (upper right) - I have no "Delete" option.

**Comment by mattl** [comment]
@robmyers take a look at this one

**Comment by rheaplex** [comment]
@cablegreen Please try now? There's a long list of permissions in the config and "delete" was missing from them. I've just added it. Hopefully this will fix that.

**Comment by cablegreen** [comment]
Fixed. Thanks! @robmyers
