### ISSUE TITLE
Give Jess access to email again

### ISSUE THREAD

**Issue by jessicacoates** [cc-archive/techstuff#30]
Hey - I tried to send an email, but I might have got the email wrong.

The password on my email has been changed, which I'm assuming was on purpose? But I was expecting a few last things from Diane and Ryan, and was hoping to copy contacts and email the staff with my personal email address etc. 

Any chance I can get access to my account again temporarily? Or has it been deleted already?

Sorry - this doesn't seem to be letting me assign anyone, either?

**Comment by mattl** [comment]
hey Jess, I'll follow up with your contacts to your personal email address. We've put an autoresponder in place for your contacts giving them your personal address too.
