### ISSUE TITLE
OER Policy Registry - two Country adds

### ISSUE THREAD

**Issue by cablegreen** [cc-archive/techstuff#32]
Hi Rob: Will you please add these two countries to the right column on: 

https://wiki.creativecommons.org/wiki/OER_Policy_Registry

Romania (3 new OER policy pages)
Slovak Republic (1 new OER policy page)

Thanks! Cable

**Comment by rheaplex** [comment]
Added and tested. I apologize for the delay.

**Comment by cablegreen** [comment]
thanks ;)
