### ISSUE TITLE
Update Cable's photo

### ISSUE THREAD

**Issue by cablegreen** [cc-archive/techstuff#33]
Hey Rob - will you please update my photo on:
http://creativecommons.org/staff#

with a not-grainy version of this photo:
https://www.dropbox.com/s/h325s4nujwdwlqi/IMG_8928.jpg?dl=0

Feel free to crop out the bank space on the right.

Thanks! - Cable

**Comment by mattl** [comment]
@cablegreen I'm going to take this on. I think it's time we moved past 100x100 photos of ourselves on the website. I'm going to figure this out in the new year.

**Comment by cablegreen** [comment]
OK - thanks Matt

**Comment by cablegreen** [comment]
Closing this - will open a ticket on the "web site" project with this and some other requests. I'm also changing my title. Thanks.

**Comment by mattl** [comment]
Please keep tickets to a single request, but file as many as you like...
however, this is the appropriate place to file them.

---

Matt Lee
Creative Commons
Austin, TX, USA
3pm-11pm UTC
