### ISSUE TITLE
CC Blog is down

### ISSUE THREAD

**Issue by cablegreen** [cc-archive/techstuff#34]
http://creativecommons.org/weblog
# 

Sorry, this page doesn't exist.

**Comment by rheaplex** [comment]
Confirmed. I _added_ some symlinks today but didn't delete any or  change the Apache config. Investigating.

**Comment by rheaplex** [comment]
There is no change in wp-config.php since last year other than changing to https.

I tried reverting standby.conf but that didn't help so I restored the latest version.

Did the end of year blog post appear and preview OK?

**Comment by mattl** [comment]
Back

**Comment by rheaplex** [comment]
Yikes. Thanks. What was it?

**Comment by mattl** [comment]
Not sure, I did update permalinks today, but I ended up making a page called "blog" and setting it as the 'posts' page in WP settings.

**Comment by rheaplex** [comment]
Nice. Thank you!
