### ISSUE TITLE
CC blog links broken

### ISSUE THREAD

**Issue by cablegreen** [cc-archive/techstuff#35]
Google search: creative commons department of education

I clicked on 1st and 3rd search results:

US Dept. of Education proposes Open Licensing Policy
Tell the Department of Education 'YES' on open licensing.

The first link goes to a CC post on: 30,000 songs licensed on Soundclick in one month
The second link goes to: Sorry, this page doesn't exist.

**Comment by mattl** [comment]
Yeah, it seems our permalinks were broken for a while over the holidays and
so some links were indexed wrong.

---

Matt Lee
Creative Commons
Austin, TX, USA
3pm-11pm UTC

**Comment by cablegreen** [comment]
Are the permalinks now fixed?  And google (and other engines) will re-index?

**Comment by mattl** [comment]
Yeah, we've asked them to be reindexed.

**Comment by cablegreen** [comment]
Thanks Matt.
