### ISSUE TITLE
Can't admin the CC-Latam mailing list

### ISSUE THREAD

**Issue by claudiorrrr** [cc-archive/techstuff#36]
The admin password it was reset or something. Now I can't log in and can't find a way to retrieve it.

http://lists.ibiblio.org/mailman/admin/cc-latam

**Comment by mattl** [comment]
Okay, took the opportunity to move the list.

This list has moved to https://creativecommons.email/mailman/listinfo/latin-america

To post a message to all the list members, send email to latin-america@creativecommons.email -- you should have a new password in your inbox too.
