### ISSUE TITLE
Scholar's Copyright Addendum Engine

### ISSUE THREAD

**Issue by rheaplex** [cc-archive/techstuff#42]
Do we have the source code for -

http://scholars.sciencecommons.org/

? And if so please could I have access to it?

I would like to take a look at it if possible but it doesn't seem to be here or in the archive projects.

Thanks.

**Comment by peterspdx** [comment]
If you can't find that, you may want to ask Mike L. He might know, or Chris W.

**Comment by rheaplex** [comment]
@peterspdx Thank you, I'll ping them if it doesn't turn up.
