### ISSUE TITLE
Cable: iMac

### ISSUE THREAD

**Issue by cablegreen** [cc-archive/techstuff#44]
Hi Matt:
My iMac in my home (CC) office is 5 years old and is showing its age.
Will you please order and send me an iMac with the following specs?
- 27"
- Fusion Drive
- 1Tb storage
  I'm happy to pay for the difference if this is more than the standard / recommended purchase.
  Thanks!
  Cable

**Comment by mattl** [comment]
I sent you a 27 inch monitor, external 1Tb drive for your laptop, plus a nice HD webcam and wireless mouse.... it'll turn your laptop into a nice powerful computer :)

**Comment by cablegreen** [comment]
Thanks Matt for the update. That's not what I want. Can you please cancel the order? I'll be happy to take the value of that purchase and order what I want to use daily ... I'm happy to cover any cost difference with personal funds.

**Comment by mattl** [comment]
I was able to cancel the monitor and the hard disk, you may receive the webcam which you can return. If you'd like to buy yourself an iMac, the cost for the monitor, hard disk, mouse and webcam is about $360... so you'd be paying about $1400 out of pocket.

**Comment by cablegreen** [comment]
Cool - many thanks. Sorry to be a trouble ;)  Closing the ticket.
